services:
  user-db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASS}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "${USER_DB_PORT}:5432"
    networks:
      - tieznet
    volumes:
      - tiez-user-db:/var/lib/postgresql
  event-db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${EVENT_DB_USER}
      POSTGRES_PASSWORD: ${EVENT_DB_PASS}
      POSTGRES_DB: ${EVENT_DB_NAME}
    ports:
      - "${EVENT_DB_PORT}:5432"
    networks:
      - tieznet
    volumes:
      - tiez-event-db:/var/lib/postgresql
  booking-db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${BOOKING_DB_USER}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASS}
      POSTGRES_DB: ${BOOKING_DB_NAME}
    ports:
      - "${BOOKING_DB_PORT}:5432"
    networks:
      - tieznet
    volumes:
      - tiez-booking-db:/var/lib/postgresql
  redis:
    platform: linux/amd64
    image: bitnami/redis:7.2.5
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - tieznet
    volumes:
      - redis-db:/bitnami/redis/data
  redisinsight:
    platform: linux/amd64
    image: redislabs/redisinsight:2.54
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    networks:
      - tieznet
    depends_on:
      - redis
volumes:
  tiez-user-db:
  tiez-event-db:
  tiez-booking-db:
  redis-db:

networks:
  tieznet: