services:
  user-db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASS}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "${USER_DB_PORT}:5432"
    networks:
      - tieznet
    volumes:
      - tiez-user-db:/var/lib/postgresql
  event-db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${EVENT_DB_USER}
      POSTGRES_PASSWORD: ${EVENT_DB_PASS}
      POSTGRES_DB: ${EVENT_DB_NAME}
    ports:
      - "${EVENT_DB_PORT}:5432"
    networks:
      - tieznet
    volumes:
      - tiez-event-db:/var/lib/postgresql
  booking-db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${BOOKING_DB_USER}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASS}
      POSTGRES_DB: ${BOOKING_DB_NAME}
    ports:
      - "${BOOKING_DB_PORT}:5432"
    networks:
      - tieznet
    volumes:
      - tiez-booking-db:/var/lib/postgresql
  redis:
    platform: linux/amd64
    image: bitnami/redis:7.2.5
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - tieznet
    volumes:
      - redis-db:/bitnami/redis/data
  redisinsight:
    platform: linux/amd64
    image: redislabs/redisinsight:2.54
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    networks:
      - tieznet
    depends_on:
      - redis
  kafka-0:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9095,1@kafka-1:9095,2@kafka-2:9095
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-0:29092,CONTROLLER://kafka-0:9095,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - tieznet
  kafka-1:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9093:9093"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9095,1@kafka-1:9095,2@kafka-2:9095
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-1:29093,CONTROLLER://kafka-1:9095,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:29093,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - tieznet
  kafka-2:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9094:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9095,1@kafka-1:9095,2@kafka-2:9095
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-2:29094,CONTROLLER://kafka-2:9095,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:29094,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - tieznet
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    ports:
      - 8888:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:29092
      KAFKA_CLUSTERS_1_NAME: kafka1
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-1:29093
      KAFKA_CLUSTERS_2_NAME: kafka2
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka-2:29094
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - tieznet
volumes:
  tiez-user-db:
  tiez-event-db:
  tiez-booking-db:
  redis-db:

networks:
  tieznet: